### ISSUE TITLE
Getting started documentation

### ISSUE THREAD

**Issue by joneshf** [5outh/nanoscope#51]
I noticed the formatting is a bit off on the getting started page. Looks like it's coming from here: https://github.com/5outh/nanoscope/blob/gh-pages/getting-started.html#L108-L119 

I was going to send a PR, but didn't know if this was auto generated. If not, expect a PR soon.

**Comment by 5outh** [comment]
It is auto-generated from here: https://github.com/5outh/nanoscope/blob/gh-pages/example.js

Are you referring to Pinky's location being formatted with a different style than Clyde's, or is there something else I'm missing.

Either way, nice catch and thanks for noticing! :)

**Comment by joneshf** [comment]
Yeah, that's what I meant.

So, how do I regenerate the html file?

**Comment by 5outh** [comment]
This was generated from https://github.com/5outh/nanoscope-site/blob/master/example.js (in the nanoscope-site repository), then compiled with Jekyll. The `gh-pages` branch of `nanoscope` is just the `_site` directory output from `jekyll build` copied over. :)

If you want to go in and fix it on nanoscope-site, that would be awesome! You can either just submit a patch there or copy over the _site directory into the gh-pages branch to fix up the actual site as well. Either way, I'll make sure the changes get pushed. Thanks again!

**Comment by joneshf** [comment]
Oh, sorry, I didn't see the other repo.

It looks like https://github.com/5outh/nanoscope-site/blob/master/_includes/first_example.md is what has to change to fix the layout, but what is https://github.com/5outh/nanoscope-site/blob/master/example.js used for then?

**Comment by 5outh** [comment]
Ah, right. The repo is a little sloppy; I think `example.js` is superfluous.

**Comment by 5outh** [comment]
Thanks @joneshf for fixing the issue on nanoscope-site so this could get fixed! :+1:
